

#platform :ios, '12.0'

target 'TestMylib_master_Example' do
  use_frameworks!
  
  pod 'TestMylib_master', :path => '../'
  
  pod 'Mux-Stats-AVPlayer', '~> 3.1.0'
  pod 'GCDWebServer', '~> 3.5.4'
  pod 'Sentry', '~> 7.31.3'
  pod 'GoogleWebRTC'
  pod  'SwiftCentrifuge'
  pod  'SwiftProtobuf', '~> 1.0'
end
